-- If already defined, return
if _runtime_global_settings_constants and _runtime_global_settings_constants.configurable_nukes then
    return _runtime_global_settings_constants
end

local prefix = "configurable-nukes-"

local runtime_global_settings_constants = {}

runtime_global_settings_constants.settings = {
    ATOMIC_BOMB_ROCKET_LAUNCHABLE = {
        type = "bool-setting",
        name = prefix .. "atomic-bomb-rocket-launchable",
        setting_type = "runtime-global",
        order = "cbd",
        default_value = false,
    },
    POLLUTION = {
        type = "double-setting",
        name = prefix .. "pollution",
        setting_type = "runtime-global",
        order = "cbe",
        default_value = 0.166,
        maximum_value = 11,
        minimum_value = 0
    },
    ATOMIC_WARHEAD_POLLUTION = {
        type = "double-setting",
        name = prefix .. "atomic-warhead-pollution",
        setting_type = "runtime-global",
        order = "cbf",
        default_value = 0.542,
        maximum_value = 11,
        minimum_value = 0,
    },
    PIN_TARGETS = {
        type = "bool-setting",
        name = prefix .. "pin-targets",
        setting_type = "runtime-global",
        order = "cca",
        default_value = true,
    },
    DO_ICBMS_REVEAL_TARGET = {
        type = "bool-setting",
        name = prefix .. "do-icbms-reveal-target",
        setting_type = "runtime-global",
        order = "ccb",
        default_value = true,
    },
    PRINT_LAUNCH_MESSAGES = {
        type = "bool-setting",
        name = prefix .. "icbms-print-launch-messages",
        setting_type = "runtime-global",
        order = "ccc",
        default_value = true,
    },
    PRINT_DELIVERY_MESSAGES = {
        type = "bool-setting",
        name = prefix .. "icbms-print-delivery-messages",
        setting_type = "runtime-global",
        order = "ccd",
        default_value = true,
    },
    --[[ ICBM ]]
    ATOMIC_BOMB_BASE_DAMAGE_MODIFIER = {
        type = "double-setting",
        name = prefix .. "atomic-bomb-base-damage-modifier",
        setting_type = "runtime-global",
        order = "cce",
        default_value = 1,
        minimum_value = 0,
        maximum_value = 11,
    },
    ATOMIC_BOMB_BASE_DAMAGE_ADDITION = {
        type = "double-setting",
        name = prefix .. "atomic-bomb-base-damage-addition",
        setting_type = "runtime-global",
        order = "ccf",
        default_value = 0,
        minimum_value = 0,
        maximum_value = 2 ^ 42,
    },
    -- ATOMIC_BOMB_BASE_DAMAGE_RADIUS_MODIFIER = {
    --     type = "double-setting",
    --     name = prefix .. "atomic-bomb-base-damage-radius-modifier",
    --     setting_type = "runtime-global",
    --     order = "ccf",
    --     default_value = 1,
    --     minimum_value = 0,
    --     maximum_value = 11,
    -- },
    ATOMIC_BOMB_BONUS_DAMAGE_MODIFIER = {
        type = "double-setting",
        name = prefix .. "atomic-bomb-bonus-damage-modifier",
        setting_type = "runtime-global",
        order = "cdd",
        default_value = 1,
        minimum_value = 0,
        maximum_value = 11,
    },
    ATOMIC_BOMB_BONUS_DAMAGE_ADDITION = {
        type = "double-setting",
        name = prefix .. "atomic-bomb-bonus-damage-addition",
        setting_type = "runtime-global",
        order = "cde",
        default_value = 0,
        minimum_value = 0,
        maximum_value = 2 ^ 42,
    },
    -- ATOMIC_BOMB_BONUS_DAMAGE_RADIUS_MODIFIER = {
    --     type = "double-setting",
    --     name = prefix .. "atomic-bomb-bonus-damage-radius-modifier",
    --     setting_type = "runtime-global",
    --     order = "cdf",
    --     default_value = 1,
    --     minimum_value = 0,
    --     maximum_value = 11,
    -- },
    ATOMIC_WARHEAD_BASE_DAMAGE_MODIFIER = {
        type = "double-setting",
        name = prefix .. "atomic-warhead-base-damage-modifier",
        setting_type = "runtime-global",
        order = "ced",
        default_value = 1,
        minimum_value = 0,
        maximum_value = 11,
    },
    ATOMIC_WARHEAD_BASE_DAMAGE_ADDITION = {
        type = "double-setting",
        name = prefix .. "atomic-warhead-base-damage-addition",
        setting_type = "runtime-global",
        order = "cee",
        default_value = 0,
        minimum_value = 0,
        maximum_value = 2 ^ 42,
    },
    -- ATOMIC_WARHEAD_BASE_DAMAGE_RADIUS_MODIFIER = {
    --     type = "double-setting",
    --     name = prefix .. "atomic-warhead-base-damage-radius-modifier",
    --     setting_type = "runtime-global",
    --     order = "cef",
    --     default_value = 1,
    --     minimum_value = 0,
    --     maximum_value = 11,
    -- },
    ATOMIC_WARHEAD_BONUS_DAMAGE_MODIFIER = {
        type = "double-setting",
        name = prefix .. "atomic-warhead-bonus-damage-modifier",
        setting_type = "runtime-global",
        order = "cfd",
        default_value = 1,
        minimum_value = 0,
        maximum_value = 11,
    },
    ATOMIC_WARHEAD_BONUS_DAMAGE_ADDITION = {
        type = "double-setting",
        name = prefix .. "atomic-warhead-bonus-damage-addition",
        setting_type = "runtime-global",
        order = "cfe",
        default_value = 0,
        minimum_value = 0,
        maximum_value = 2 ^ 42,
    },
    -- ATOMIC_WARHEAD_BONUS_DAMAGE_RADIUS_MODIFIER = {
    --     type = "double-setting",
    --     name = prefix .. "atomic-warhead-bonus-damage-radius-modifier",
    --     setting_type = "runtime-global",
    --     order = "cff",
    --     default_value = 1,
    --     minimum_value = 0,
    --     maximum_value = 11,
    -- },
    ICBM_PERFECT_GUIDANCE = {
        type = "bool-setting",
        name = prefix .. "icbms-perfect-guidance",
        setting_type = "runtime-global",
        order = "cjd",
        default_value = false,
    },
    ICBM_PLANET_MAGNITUDE_AFFECTS_TRAVEL_TIME = {
        type = "bool-setting",
        name = prefix .. "icbms-planet-magnitude-affects-travel-time",
        setting_type = "runtime-global",
        order = "cje",
        default_value = true,
    },
    ICBM_PLANET_MAGNITUDE_MODIFIER = {
        type = "double-setting",
        name = prefix .. "icbms-magnitude-modifier",
        setting_type = "runtime-global",
        order = "cjf",
        default_value = 1,
        minimum_value = (1 / 2) ^ 11,
        maximum_value = 11,
    },
    ICBM_TRAVEL_MULTIPLIER = {
        type = "double-setting",
        name = prefix .. "icbms-travel-multiplier",
        setting_type = "runtime-global",
        order = "cjg",
        default_value = 1,
        minimum_value = 0,
        maximum_value = 2 ^ 11
    },
    ICBM_GUIDANCE_DEVIATION_THRESHOLD = {
        type = "double-setting",
        name = prefix .. "icbms-guidance-deviation-threshold",
        setting_type = "runtime-global",
        order = "cjh",
        default_value = 0.25,
        minimum_value = 0,
        maximum_value = 1
    },
    ICBM_CIRCUIT_ALLOW_TARGETING_ORIGIN = {
        type = "bool-setting",
        name = prefix .. "icbms-circuit-allow-targeting-origin",
        setting_type = "runtime-global",
        order = "dcc",
        default_value = false,
    },
    -- ICBM_CIRCUIT_PRINT_FLIGHT_MESSAGES = {
    --     type = "bool-setting",
    --     name = prefix .. "icbms-circuit-print-flight-messages",
    --     setting_type = "runtime-global",
    --     order = "dcd",
    --     default_value = false,
    -- },
    ICBM_CIRCUIT_PRINT_LAUNCH_MESSAGES = {
        type = "bool-setting",
        name = prefix .. "icbms-circuit-print-launch-messages",
        setting_type = "runtime-global",
        order = "dcd",
        default_value = false,
    },
    ICBM_CIRCUIT_PRINT_DELIVERY_MESSAGES = {
        type = "bool-setting",
        name = prefix .. "icbms-circuit-print-delivery-messages",
        setting_type = "runtime-global",
        order = "dce",
        default_value = false,
    },
    ICBM_CIRCUIT_PIN_TARGETS = {
        type = "bool-setting",
        name = prefix .. "icbms-circuit-print-pin-targets",
        setting_type = "runtime-global",
        order = "dcf",
        default_value = false,
    },
}

runtime_global_settings_constants.configurable_nukes = true

local _runtime_global_settings_constants = runtime_global_settings_constants

return runtime_global_settings_constants