data:extend({
    {
        type = "recipe",
        name = "payloader",
        icon = "__configurable-nukes__/graphics/icons/payloader.png",
        icon_size = 64,
        category = "crafting-with-fluid",
        subgroup = "production-machine",
        enabled = false,
        energy_required = 6,
        ingredients = {
            { type = "item", name = "assembling-machine-3", amount = 1, },
            { type = "item", name = "bulk-inserter", amount = 2, },
            { type = "item", name = "steel-chest", amount = 2, },
            { type = "item", name = "processing-unit", amount = 4, },
            { type = "item", name = "low-density-structure", amount = 4, },
            { type = "item", name = "concrete", amount = 50, },
            { type = "fluid", name = "lubricant", amount = 100, },
        },
        results = {
            { type = "item", name = "payloader", amount = 1, },
        },
    },
    {
        type = "recipe",
        name = "payload-add",
        icons = {
            {
                icon = "__base__/graphics/item-group/military.png",
                icon_size = 128,
                shift = { -12, -12 },
                scale = (1 / 4),
                draw_background = true,
            },
            {
                icon = "__configurable-nukes__/graphics/icons/payload-vehicle.png",
                icon_size = 173,
                shift = { 6, 6 },
                draw_background = true,
            },
            {
                icon = "__configurable-nukes__/graphics/technology/object-to-object-arrow.png",
                icon_size = 256,
                shift = { -2, -2 },
                scale = (1 / 5),
                floating = true,
            },
        },
        icon_size = 64,
        category = "payload-change",
        subgroup = "payload",
        enabled = false,
        hide_from_player_crafting = true,
        hide_rom_flow_stats = true,
        energy_required = 1,
        ingredients = {},
        results = {},
    },
    {
        type = "recipe",
        name = "payload-remove",
        icons = {
            {
                icon = "__configurable-nukes__/graphics/icons/payload-vehicle.png",
                icon_size = 173,
                shift = { -12, -12 },
                scale = (1 / 4),
                draw_background = true,
            },
            {
                icon = "__base__/graphics/item-group/military.png",
                icon_size = 128,
                shift = { 6, 6 },
                draw_background = true,
            },
            {
                icon = "__configurable-nukes__/graphics/technology/object-to-object-arrow.png",
                icon_size = 256,
                shift = { -2, -2 },
                scale = (1 / 5),
                floating = true,
            },
        },
        icon_size = 64,
        category = "payload-change",
        subgroup = "payload",
        enabled = false,
        hide_from_player_crafting = true,
        hide_rom_flow_stats = true,
        energy_required = 1,
        ingredients = {},
        results = {},
    },
})